# Generated by Django 4.2.3 on 2023-10-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='placehold.jpg', upload_to='profile_pics'),
        ),
    ]
