# Generated by Django 4.2.3 on 2023-10-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://ibdhaalkhaleej.com/wp-content/uploads/2022/10/woocommerce-placeholder-600x600-1.png', max_length=200),
        ),
    ]
