# Generated by Django 4.2.3 on 2023-10-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ImageField(default='profilepic.jpg', upload_to='profile_pics'),
        ),
    ]
